import { test, expect } from "./fixtures/garden";

test("renders explicit low-confidence and omitted-crop warnings from a fixed response fixture", async ({ page }) => {
  // Rendering contract only: this literal response is not generated by the planner and is not persisted.
  await page.route("**/api/garden-plan", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        saved: true,
        inputFingerprint: "fixed-rendering-contract",
        generatedAt: "2026-10-04T12:00:00.000Z",
        plan: {
          spaces: [
            {
              space: { id: "fixture-bed", name: "Skrzynia e2e", widthCm: 120, lengthCm: 80 },
              positions: [
                {
                  spaceId: "fixture-bed",
                  cropId: "marchew",
                  xCm: 15,
                  yCm: 15,
                  row: 0,
                  column: 0,
                  spacing: { inRowCm: 30, betweenRowsCm: 30 },
                  confidence: "low",
                  stage: "final_planting",
                  neighbors: [],
                  placementReason: {
                    category: "target_mix",
                    detail: "Literal fixture placement.",
                    constrainedByCropIds: [],
                    rejectedGeometryCandidates: 0,
                  },
                },
              ],
              status: "complete",
            },
          ],
          cropSummaries: [
            {
              cropId: "marchew",
              targetPercentage: 100,
              actualPercentage: 100,
              actualCount: 1,
              dataConfidence: "low",
              spacingStage: "final_planting",
            },
          ],
          omissions: [{ cropId: "pomidor", reason: "missing_spacing", detail: "Brak potwierdzonej rozstawy." }],
          conflicts: [],
          warnings: ["Dane rozstawy mają niską pewność; sprawdź źródła przed użyciem planu."],
          metrics: { candidateChecks: 1, supportedNeighbors: 0, cautionNeighbors: 0, limitReached: false },
        },
      }),
    }),
  );

  await page.goto("/garden");
  await page.getByRole("button", { name: "Wygeneruj plan", exact: true }).click();
  const planner = page.getByRole("region", { name: "Układ działki", exact: true });
  await expect(planner).toHaveAttribute("data-plan-status", "current");
  await expect(planner).toContainText("Dane rozstawy mają niską pewność");
  const layout = page.getByRole("region", { name: "Szczegóły wygenerowanego układu" });
  await expect(layout).toContainText("Uprawy bez wyznaczonej pozycji");
  await expect(layout).toContainText("pomidor Faworyt");
  await expect(layout).toContainText("Pewność danych");
  await expect(layout).toContainText("niska");
});
